version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: task-postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      TZ: Asia/Almaty
      PGTZ: Asia/Almaty
    ports:
      - "5435:5432"  # This port mapping allows connection from IntelliJ
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: taskuser
      SPRING_DATASOURCE_PASSWORD: taskpass
      TZ: Asia/Almaty
      JAVA_TOOL_OPTIONS: -Duser.timezone=Asia/Almaty
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  task-network:
    driver: bridge